name: Build NanoPi R6C/R6S Orange Pi 5/5-plus Rockchip BSP kernel
on: [push]

jobs:
    build:
        name: Prepare and Build NanoPi R6C/R6S Orange Pi 5/5-plus Images
        runs-on: self-hosted

        steps:




            - name: Checkout
              uses: actions/checkout@v3

            - name: Build OpenWrt
              run: |
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci

                wget https://gist.githubusercontent.com/mj22226/f6db007367a22a31f9cb1c109a032b45/raw/be368c4f1605f652a001d81548c3a3e14adf6cb7/luci-app-diskman.patch
                git apply luci-app-diskman.patch
                cd -
                sed -i "70s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "83s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "193s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "209s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd

                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                cp .github/workflows/config.buildinfo .config
                make defconfig
                wget https://gist.githubusercontent.com/mj22226/8fe3f95119c0ea42794f8241042b60d5/raw/1e0cb3155a8df2fd36a18629f08c51d3c90ecff9/0001-local-key.patch
                git apply 0001-local-key.patch
                rm 0001-local-key.patch
                make download -j55
                make tools/install -j$(nproc)
                make toolchain/install -j$(nproc)
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf build_dir
                tar -cvf rockchip-images.tar bin/targets/rockchip/armv8

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: rockchip-images
                path: rockchip-images.tar

    release:
          name: Make a release
          runs-on: ubuntu-latest
          needs: build

          steps:
            - name: Download the image artifacts
              uses: actions/download-artifact@v3
              with:
                name: rockchip-images

            - name: Extract the image artifacts
              run: tar xf rockchip-images.tar

            - name: Create a release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: false
                title: "NanoPi R6C/R6S Orange Pi 5/5-plus BSP Kernel 5.10.110"
                automatic_release_tag: "rk3588-v22.03.5"
                files: bin/targets/rockchip/armv8/*
